### ISSUE TITLE
[Bug Report].net core开发webapi时，自有模式的永久授权，Token写入本地txt时路径错误

### ISSUE THREAD

**Issue by mw248** [QcCoding/Qc.YilianyunSdk#1]
DefaultYilianyunSdkHook.cs中SaveToken方法，Token写入本地txt时，使用的：
string savePath = Path.Combine(Path.GetFullPath(_yilianyunConfig.SaveTokenDirPath), code + ".txt");
这个拼接出来的路径在用.net core开发webapi时，获取上层目录时，拼接出一个错误路径，到执行程序目录外面的更上一层去了，导致无法写入Token到本地，不写入Token本地的话，AuthTerminal进行终端永久授权时，就会生成一个新的Token，导致旧Token过期。

**Comment by yimogit** [comment]
@mw248 可以根据自己的需要实现 hook 哈。

**Comment by mw248** [comment]
好的
